CREATE TABLE BERDOTT.GAME (
        IDGA NUMBER NOT NULL,
        NAME VARCHAR2(50 BYTE) NOT NULL,
        PASSWORD VARCHAR2(50 BYTE) NOT NULL,
        WORD VARCHAR2(50 BYTE) NOT NULL,
        STATUS VARCHAR2(10 BYTE) NOT NULL,
        DATECRE TIMESTAMP NOT NULL,
        CONSTRAINT "PK_GAME" PRIMARY KEY ( "IDGA" )
	);

CREATE TABLE BERDOTT.ATTEMPT (
        IDAT NUMBER NOT NULL,
        IDGA NUMBER NOT NULL,
        LETTER VARCHAR2(1 BYTE) NOT NULL,
        STATUS VARCHAR2(10 BYTE) NOT NULL,
        DATECRE TIMESTAMP NOT NULL,
        CONSTRAINT "PK_ATTEMPT" PRIMARY KEY ( "IDAT" ),
        CONSTRAINT FK_ATTEMPT_GAME FOREIGN KEY (IDGA)
        REFERENCES BERDOTT.GAME (IDGA)
	);

CREATE SEQUENCE BERDOTT.ATTEMPT_SEQ START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE BERDOTT.GAME_SEQ START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;