CREATE TABLE BERDOTT.GAME (
        IDGA NUMBER NOT NULL,
        NAME VARCHAR2(50 BYTE) NOT NULL,
        PASSWORD VARCHAR2(50 BYTE) NOT NULL,
        WORD VARCHAR2(50 BYTE) NOT NULL,
        STATUS VARCHAR2(10 BYTE) NOT NULL,
        DATECRE TIMESTAMP NOT NULL,
        CONSTRAINT "PK_GAME" PRIMARY KEY ( "IDGA" )
	);

CREATE TABLE BERDOTT.ATTEMPT (
        IDAT NUMBER NOT NULL,
        IDGA NUMBER NOT NULL,
        LETTER VARCHAR2(1 BYTE) NOT NULL,
        STATUS VARCHAR2(10 BYTE) NOT NULL,
        DATECRE TIMESTAMP NOT NULL,
        CONSTRAINT "PK_ATTEMPT" PRIMARY KEY ( "IDAT" ),
        CONSTRAINT FK_ATTEMPT_GAME FOREIGN KEY (IDGA)
        REFERENCES BERDOTT.GAME (IDGA)
	);

CREATE SEQUENCE BERDOTT.ATTEMPT_SEQ START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE BERDOTT.GAME_SEQ START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


-- mySql version

CREATE TABLE game (
    IDGA INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    WORD VARCHAR(50) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    DATECRE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (IDGA)
);

CREATE TABLE attempt (
    IDAT INT NOT NULL AUTO_INCREMENT,
    IDGA INT NOT NULL,
    LETTER CHAR(1) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    DATECRE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (IDAT),
    FOREIGN KEY (IDGA) REFERENCES game(IDGA)
);

INSERT INTO game (NAME, PASSWORD, WORD, STATUS, DATECRE) VALUES
('Hangman1', 'pass123', 'APPLE', 'ACTIVE', NOW()),
('Hangman2', 'secret', 'BANANA', 'FINISHED', NOW()),
('Hangman3', 'guessme', 'ORANGE', 'ACTIVE', NOW());



INSERT INTO attempt (IDGA, LETTER, STATUS, DATECRE) VALUES
(1, 'A', 'CORRECT', NOW()),
(1, 'B', 'WRONG', NOW()),
(1, 'P', 'CORRECT', NOW()),
(2, 'B', 'CORRECT', NOW()),
(2, 'N', 'CORRECT', NOW()),
(3, 'X', 'WRONG', NOW()),
(3, 'O', 'CORRECT', NOW());
commit;
